version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mates_saas
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: mates_saas
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  ai-server:
    build: ./ai-server
    ports:
      - "5000:5000"
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
