name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "" | docker login -u "" --password-stdin

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy to production
        run: ./scripts/deploy.sh
