name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker-compose build

      - name: Run backend tests
        run: docker-compose run backend php artisan test

      - name: Run frontend tests
        run: docker-compose run frontend npm test
